
CREATE TABLE usuario (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nome VARCHAR2(100) NOT NULL,
                         email VARCHAR2(100) NOT NULL,
                         senha VARCHAR2(100) NOT NULL,
                         role VARCHAR2(50) NOT NULL
);

-- Tabela carteira
CREATE TABLE carteira (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          usuario_id NUMBER NOT NULL,
                          saldo NUMBER(10,2) NOT NULL,
                          CONSTRAINT fk_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

INSERT INTO usuario (nome, email, senha, role)
VALUES ('Pedro Gustavo', 'pedrojuchimiul@fiap', '261204', 'CLIENTE');

INSERT INTO usuario (nome, email, senha, role)
VALUES ('Empresa XYZ', 'contato@xyz.com', 'senha123', 'EMPRESA');

-- Para pegar o ID gerado, você pode usar RETURNING ou sequências, mas aqui assumimos CURRVAL
-- Inserindo carteiras vinculadas aos usuários
INSERT INTO carteira (usuario_id, saldo)
VALUES (1, 1000.00);

INSERT INTO carteira (usuario_id, saldo)
VALUES (2, 5000.00);


-- Selects

SELECT * FROM usuario;
SELECT * FROM carteira;
